### ISSUE TITLE
Script gets stuck after trying to send an invalid message

### ISSUE THREAD

**Issue by PikaDude** [plasticuproject/cleverbotfree#2]
Trying to submit a message such as "<html>" makes cleverbot.com prevent the message from being sent, and then seemingly gets the script stuck as the message box is not automatically cleared due to the error and any future messages get appended but also get stuck since the original invalid message is still there.

**Comment by plasticuproject** [comment]
@PikaDude 
I could not replicate your issue.
```
(clevererbot) plasticuproject@home:~/Envs/clevererbot$ ./clevererbot.py 

[-] Connecting to Cleverbot.com...
[-] Have a conversation with CleverBot...
[-] Just type "quit" to end the conversation

 USER: hello
 CLEVERBOT:  How are you doing?
 USER: ""
 CLEVERBOT:  Are you married?
 USER: "'"
 CLEVERBOT:  I'm bored.
 USER: `~!@#$%^&*()_-+=:;"'?/>.<<
 CLEVERBOT:  M.
 USER: quit
(clevererbot) plasticuproject@home:~/Envs/clevererbot$
```
Could you provide more information? Maybe it's your implementation that's causing the issue?
I have tried to replicate the issue with multiple implementations with no success.

**Comment by PikaDude** [comment]
Sorry, I made a mistake, the script crashes if you try to send an invalid message. In my setup, I have the script set to stay alive in the result of an error, which causes the issue I said earlier. Regardless, simply sending any form of html code will cause the script to crash. Here is a simple implementation that causes the error.
```python
import cleverbotfree.cbfree
import sys
cb = cleverbotfree.cbfree.Cleverbot()

def chat():
    response = cb.single_exchange("<html>")
    print(response)
    cb.browser.close()
    sys.exit()

chat()
```
```
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    chat()
  File "main.py", line 6, in chat
    response = cb.single_exchange("<html>")
  File "C:\Users\[Redacted]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\cleverbotfree\cbfree.py", line 114, in single_exchange
    self.get_response()
  File "C:\Users\[Redacted]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\cleverbotfree\cbfree.py", line 81, in get_response
    line = self.browser.find_element_by_id('line1')
  File "C:\Users\[Redacted]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\[Redacted]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\[Redacted]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\[Redacted]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\selenium\webdriver\remote\errorhandler.py", line 241, in check_response
    raise exception_class(message, screen, stacktrace, alert_text)
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: None
Message: Dismissed user prompt dialog: Your input contains multiple lines or HTML. Please try again.
```

**Comment by plasticuproject** [comment]
Okay, I understand now. Nice catch! I'll add some kind of regex filtering/sanitation or error handling soon. In the meantime you could probably just add a filter to your implementation.

Thank you for exposing this.

**Comment by PikaDude** [comment]
No worries. I found that cleverbot.com uses the following regex's to check for invalid messages:
`/<\/?[a-z]+>|<DOCTYPE/i`
`/<[^>]+>/g`
and the presence of `\n` and `\r`
I would submit a PR but my python isn't very good.

**Comment by plasticuproject** [comment]
I added a filter. Let me know if there are still problems. If not please close the issue. Thanks again.

**Comment by PikaDude** [comment]
Everything seems to be working just fine now! Thanks for the filter.
