### ISSUE TITLE
ModuleNotFoundError: No module named 'playwright._impl._api_types'

### ISSUE THREAD

**Issue by JXSnack** [plasticuproject/cleverbotfree#27]
I did `pip install cleverbotfree` and `playwright install firefox`. 
This is the code I used:
```python
import asyncio
from cleverbotfree import CleverbotAsync
from cleverbotfree import Cleverbot

@Cleverbot.connect
def chat(bot, user_prompt, bot_prompt):
    """Example code using cleverbotfree sync api with decorator."""
    while True:
        user_input = input(user_prompt)
        if user_input == "quit":
            break
        reply = bot.single_exchange(user_input)
        print(bot_prompt, reply)
    bot.close()

chat("User: ", "Cleverbot:")


@CleverbotAsync.connect
async def async_chat(bot, user_prompt, bot_prompt):
    """Example code using cleverbotfree async api with decorator."""
    while True:
        user_input = input(user_prompt)
        if user_input == "quit":
            break
        reply = await bot.single_exchange(user_input)
        print(bot_prompt, reply)
    await bot.close()

asyncio.run(async_chat("User: ", "Cleverbot:"))
```

Stacktrace:
```python
Traceback (most recent call last):
  File "/Users/joram/PycharmProjects/SnackBagAI/ai.py", line 2, in <module>
    from cleverbotfree import CleverbotAsync
  File "/Users/joram/PycharmProjects/SnackBagAI/.venv/lib/python3.12/site-packages/cleverbotfree/__init__.py", line 26, in <module>
    from playwright._impl._api_types import TimeoutError as PwTimeout
ModuleNotFoundError: No module named 'playwright._impl._api_types'
```
Python 3.12.0
MacOS 14.0 Sonoma, M1 Chip

**Comment by Roester1** [comment]
sad

**Comment by plasticuproject** [comment]
@JXSnack Should be fixed in latest version.
