### ISSUE TITLE
"Unable to find a matching set of capabilities"

### ISSUE THREAD

**Issue by AdinAck** [plasticuproject/cleverbotfree#5]
Trying to run the example script returns this error after a short pause.

Exact error:

Traceback (most recent call last):
  File "C:\Users\rhett\Desktop\ai.py", line 3, in <module>
    cb = cleverbotfree.cbfree.Cleverbot()
  File "C:\Program Files\Python37\lib\site-packages\cleverbotfree\cbfree.py", line 42, in __init__
    self.browser = webdriver.Firefox(options=self.opts)
  File "C:\Program Files\Python37\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    keep_alive=True)
  File "C:\Program Files\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Program Files\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Program Files\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by plasticuproject** [comment]
@AdinAck can you provide your geckodriver version and firefox version so I can try to duplicate?

**Comment by AdinAck** [comment]
I don't have firefox...do I need firefox? XD
Geckodriver is latest version, just downloaded from their repo.

**Comment by AdinAck** [comment]
Ok I downloaded firefox...that fixed it... face palm
