### ISSUE TITLE
[Errno 8] Exec Format Error

### ISSUE THREAD

**Issue by jethr0-1** [plasticuproject/cleverbotfree#8]
When trying to run single_chat.py (with python 2, not 3) it returns the following error:

`Traceback (most recent call last):
  File "single_chat.py", line 10, in <module>
    cb = cleverbotfree.cbfree.Cleverbot()
  File "/home/pi/.local/lib/python2.7/site-packages/cleverbotfree/cbfree.py", line 42, in __init__
    self.browser = webdriver.Firefox(options=self.opts)
  File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error`

What's going on?

**Comment by plasticuproject** [comment]
I'm not sure, as I have only tested this for python 3, and written it exclusively for python 3, as listed in the requirements in the readme. It looks as though it's maybe the way that the webdriver uses the subprocess module. That may not be compatible for python 2. Maybe it's trying to use a method that doesn't exist in subprocess for python 2, but exists in python 3.

**Comment by plasticuproject** [comment]
Closing.
